# Build with:
#   docker build -f Dockerfile-api -t app/api .
# Push
#   docker push gmhafiz/api:latest
# Run with
#   docker run --rm -it -p 3080:3080 --name api app/api
# Healthiness
#   curl -v localhost:3080/healthz

FROM golang:1.19 AS src

WORKDIR /go/src/app/

# Copy dependencies first to take advantage of Docker caching
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

# Insert version using git tag and latest commit hash
# Build Go Binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./api cmd/api/main.go;

FROM gcr.io/distroless/static-debian11

LABEL com.example.maintainers="User <author@example.com>"

WORKDIR /App

COPY --from=src /go/src/app/api /App/api


EXPOSE 3080

ENTRYPOINT ["/App/api"]
