# Build with:
#   TAG=$(git rev-parse HEAD)
#   docker build -f Dockerfile-api -t gmhafiz/api:$TAG .
# Push
#   docker push gmhafiz/api:$TAG
# Run with
#   docker run --rm -it -p 3080:3080 --name api gmhafiz/api:$TAG
# Healthiness
#   curl -v localhost:3080/healthz

FROM golang:1.21 AS build

WORKDIR /go/src/app/

# Copy dependencies first to take advantage of Docker caching
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

# Insert version using git tag and latest commit hash
# Build Go Binary
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./api cmd/api/main.go

FROM gcr.io/distroless/static-debian12:nonroot

LABEL com.example.maintainers="User <author@example.com>"

COPY --from=build /go/src/app/api /usr/local/bin/api

EXPOSE 3080

ENTRYPOINT ["/usr/local/bin/api"]
